### ISSUE TITLE
how can i judge the share is successful

### ISSUE THREAD

**Issue by RRRMannn** [OpenFlutter/fluwx#99] opened 2019-08-28 01:35 UTC

**Comment by JarvanMo** [comment] 2019-08-28 01:38
Duplicate of #92

**Comment by JarvanMo** [comment] 2019-08-28 01:41
Developers will never know the real result of sharing since the official behavior changed.

**Comment by RRRMannn** [comment] 2019-08-28 01:42
got it ,thanks bro




------------------ 原始邮件 ------------------
发件人: "JarvanMo"<notifications@github.com>; 
发送时间: 2019年8月28日(星期三) 上午9:41
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>; 
抄送: "满、"<975254814@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [OpenFlutter/fluwx] how can i judge the share is successful (#99)




Developers will never know the real result of sharing since the official behavior changed.
 
&mdash;

**Closed** 2019-08-28 01:43 UTC
Labels: duplicate
