### ISSUE TITLE
 fluwx.register   used failed

### ISSUE THREAD

**Issue by YoungCC2** [OpenFlutter/fluwx#55] opened 2019-04-01 13:02 UTC
`  _initFluwx() async {
    await fluwx.register(
        appId: "xxxxxxxxxxxx",
        doOnAndroid: true,
        doOnIOS: true,
        enableMTA: false);
        var result = await fluwx.isWeChatInstalled();
        print("is installed $result");
  }`

printed   is installed false.

**Comment by JarvanMo** [comment] 2019-04-01 13:10
多翻issue 
Duplicate of #38

**Closed by JarvanMo** 2019-04-01 13:10 UTC

**Comment by YoungCC2** [comment] 2019-04-01 13:21
e,模拟器没有安装微信 调用fluwx.isWeChatInstalled() 会返回false.   所以这个地方是合适的返回
