### ISSUE TITLE
Unhandled Exception: PlatformException(wxapi not configured, WxApi Not Registered, null)

### ISSUE THREAD

**Issue by hqwlkj** [OpenFlutter/fluwx#186] opened 2020-01-17 08:49 UTC
**Describe the bug**

Unhandled Exception: PlatformException(wxapi not configured, WxApi Not Registered, null)

**To Reproduce**
我的代码
 ```
@override
  void initState() {
    super.initState();
    _initFluwx();
  }

_initFluwx() async {
    await fluwx.registerWxApi(
        // 这里需要在微信开放平台创建应用后填写  https://open.weixin.qq.com/
        appId: "appId",
        doOnAndroid: true,
        doOnIOS: true,
        universalLink: "https://test.universalLink.com/wx/app/");

    /// 初始化 fluwx 分享组件
    _wxShare = fluwx.responseFromShare.listen((data) {
      LogUtil.e('data.errCode:${data.errCode}', tag: '微信分享监听：');
      if (data.errCode < 0) {
        Utils.showToast("分享失败");
      } else {
        Utils.showToast("分享成功");
      }
    });
  }

// 分享调用

// 打印各种属性以验证文件保存成功
        LogUtil.e(file.path, tag: 'file.path:');
        LogUtil.e(file.statSync(), tag: 'file.statSync: ');
        String _imagePath = 'file://${file.path}';
        String _thumbnail = "assets://images/icon_logo.png";
        WeChatShareImageModel _model = fluwx.WeChatShareImageModel(
            image: _imagePath,
            thumbnail: _thumbnail,
            transaction: _imagePath,
            scene: scene,
            description: "这里就一一段描述！");
        fluwx.shareToWeChat(_model);

```

**Flutter Version:**
fluwx: ^1.2.1+1

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)

• No issues found!

**Testing Platform:**
Android or iOS?

iOS
Android 正常，但是ios 有问题

**Comment by JarvanMo** [comment] 2020-01-17 08:52
Duplicate of #124

**Closed by JarvanMo** 2020-01-17 08:52 UTC
