### ISSUE TITLE
fluwx2.0.9版本，调分享，按照demo设置缩略图，找不到缩略图错误，app崩溃

### ISSUE THREAD

**Issue by ZeroMoment** [OpenFlutter/fluwx#236] opened 2020-05-10 16:02 UTC
按照文档，定义缩略图目录，分享报错：找不到图片资源，错误如下

`
E/AndroidRuntime(22956): FATAL EXCEPTION: main
E/AndroidRuntime(22956): Process: com.guangsu.job.joboversea, PID: 22956
E/AndroidRuntime(22956): java.io.FileNotFoundException: flutter_assets//ic_sharelogo.png
E/AndroidRuntime(22956): 	at android.content.res.AssetManager.nativeOpenAssetFd(Native Method)
E/AndroidRuntime(22956): 	at android.content.res.AssetManager.openFd(AssetManager.java:857)
E/AndroidRuntime(22956): 	at com.jarvan.fluwx.handlers.FluwxShareHandlerCompat$assetFileDescriptor$1.invoke(FluwxShareHandler.kt:57)
E/AndroidRuntime(22956): 	at com.jarvan.fluwx.handlers.FluwxShareHandlerCompat$assetFileDescriptor$1.invoke(FluwxShareHandler.kt:48)
E/AndroidRuntime(22956): 	at com.jarvan.fluwx.io.WeChatImage$Companion.createWeChatImage(WeChatImages.kt:132)
E/AndroidRuntime(22956): 	at com.jarvan.fluwx.handlers.FluwxShareHandler$DefaultImpls.readThumbnailByteArray(FluwxShareHandler.kt:254)
E/AndroidRuntime(22956): 	at com.jarvan.fluwx.handlers.FluwxShareHandler$shareWebPage$1.invokeSuspend(FluwxShareHandler.kt:221)
E/AndroidRuntime(22956): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(22956): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
E/AndroidRuntime(22956): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(22956): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(22956): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(22956): 	at android.app.ActivityThread.main(ActivityThread.java:7695)
E/AndroidRuntime(22956): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22956): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime(22956): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/Process (22956): Sending signal. PID: 22956 SIG: 9
`

我的工程目录以及调用如下图所列，应该没有毛病才对。

![image](https://user-images.githubusercontent.com/19282996/81504092-7292f600-92f8-11ea-87c8-70a956f0dc7d.png)

![image](https://user-images.githubusercontent.com/19282996/81504165-c998cb00-92f8-11ea-9870-a996ef19e708.png)

![image](https://user-images.githubusercontent.com/19282996/81504173-d61d2380-92f8-11ea-9a1d-8b59c40f7ac1.png)

很懵逼，求大佬们指导。

**Comment by JarvanMo** [comment] 2020-05-11 10:55
Duplicate of #214

**Closed by JarvanMo** 2020-05-11 10:55 UTC
